#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

PKG="rancher/confd"

rm -rf bin/*
mkdir -p bin

for platform in darwin linux; do \
  echo "$(date) - Building ${platform}"
  GOOS=$platform GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w -X main.GitSHA=${COMMIT} -X main.Version=${VERSION}" -o bin/confd-${VERSION}-$platform-amd64; \
  if [ $platform == linux ]; then \
  GOOS=$platform GOARCH=arm CGO_ENABLED=0 go build -ldflags="-s -w -X main.GitSHA=${COMMIT} -X main.Version=${VERSION}" -o bin/confd-${VERSION}-linux-arm; \
  GOOS=$platform GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w -X main.GitSHA=${COMMIT} -X main.Version=${VERSION}" -o bin/confd-${VERSION}-linux-arm64; \
  fi; \
  echo "$(date) - Finished building ${platform}"
done

cd bin/
ls
